# Based on https://github.com/mvdan/github-actions-golang
# Freshen this.

on: [push, pull_request]
name: edwood

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      acmeshell: sh

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Go tests
      run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

    - name: Build with duitdraw on non-windows systems
      if: matrix.os != 'windows-latest'
      run: go get -tags 'duitdraw mux9p' -t -v ./...

    - name: Run go vet
      run: go vet .

    - name: Install staticcheck and misspell
      run: |
        go get honnef.co/go/tools/cmd/staticcheck@v0.0.1-2020.1.5
        go get github.com/client9/misspell/cmd/misspell@v0.3.4
      working-directory: /
      shell: bash

    - name: Check if 'go get' modified go.mod file
      run: git diff --exit-code

    - name: Run staticcheck
      run: staticcheck -checks inherit,-U1000,-SA4003 ./...

    - name: Run misspell
      run: misspell -error .

    - name: Check gofmt
      run: diff -u <(echo -n) <(gofmt -d -s .)
      shell: bash

    - name: Upload coverage to codecov
      # codecov can't seem to combine reports from multiple OSes correctly
      if: matrix.os == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash)
